default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= ENV["DB_NAME"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
